name: Deploy Vue
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Vue build
    steps:
    - uses: actions/checkout@v2
    - uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16
    - run: yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: files
        path: dist
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Vue deploy
    steps:
    - uses: actions/download-artifact@v2
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        cname: ticketsystem-hci.dev001.projects.amatzen.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./files